# Generated by Django 4.1.5 on 2023-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minmun_amount',
            new_name='coupon_minmun_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_dis_amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
