# Generated by Django 4.1.5 on 2023-03-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variantoptions_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantoptions',
            name='unit',
        ),
    ]
