# Generated by Django 4.1.5 on 2023-03-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variantoptions_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
