# Generated by Django 4.1.5 on 2023-03-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='phone_number',
        ),
    ]
