# Generated by Django 4.1.5 on 2023-03-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_userdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
