# Generated by Django 4.1.5 on 2023-03-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_userdetails_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerVedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banVedio', models.FileField(upload_to='banVedio')),
                ('description', models.CharField(blank=True, default='No descrition added]', max_length=250, null=True)),
            ],
        ),
    ]
