# Generated by Django 4.1.5 on 2023-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_bannervedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catewise_dicount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
