# Generated by Django 4.1.5 on 2023-03-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variantoptions_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannervedio',
            name='banVedio',
        ),
    ]
