# Generated by Django 4.1.5 on 2023-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_bannervedio_banvedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannervedio',
            name='banVedio',
            field=models.ImageField(default='I', upload_to='banVedio'),
        ),
    ]
